services:
  web:
    build: frontend/.
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/frontend
  api:
    build: backend/.
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/backend
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'S45910538JJK'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db: